version: "3.8"

services:
  retriever:
    image: ghcr.io/classicrockfan/waittimesml/retriever:latest
    container_name: retriever
    restart: unless-stopped
    # env_file:
    # - stack.env

  db:
    image: ghcr.io/classicrockfan/waittimesml/db:latest
    container_name: db
    restart: unless-stopped
    #env_file:
    volumes:
      - waittime-db-data:/var/lib/mysql

volumes:
  waittime-db-data:
    driver: local
